[package]
name = "tpl_mutex"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Support for mutual exclusion across Task Priority Levels (TPLs)."

[lib]
path = "src/tpl_mutex.rs"

[dependencies]
r-efi = { workspace = true }
boot_services = { workspace = true }

[dev-dependencies]
# To avoid circular dependencies, cargo-release skips dev dependencies when evaluating the release order for
# cargo-release, however they are still used when verifying the package is compileable. Any dev-dependency that is
# local to the workspace should be added via `path` instead of `workspace = true` so that that it does not fail to
# compile due to the dev-dependency not being published yet.
boot_services = { path="../../sdk/boot_services", features = ["mockall"] }
mockall = { workspace = true }
