[package]
name = "section_extractor"
version = "7.0.0"
edition = "2021"
readme = "README.md"
description = "UEFI section extractor implementations."
license.workspace = true
repository.workspace = true

[lib]
name = "section_extractor"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
uefi_sdk = { workspace = true }
mu_pi = { workspace = true }
r-efi = { workspace = true }

# brotli support.
brotli-decompressor = { version= "4.0.0", default-features = false, optional = true}
alloc-no-stdlib = { version = "~2.0", optional = true}

# uefi decompress support.
mu_rust_helpers = { workspace = true, optional = true, features = ["uefi_decompress"]}

#crc32 support.
crc32fast = { version = "1.4", default-features = false, optional = true}

[features]
default = ["brotli", "uefi_decompress", "crc32"]
std = []
brotli = ["dep:brotli-decompressor", "dep:alloc-no-stdlib"]
uefi_decompress = ["dep:mu_rust_helpers"]
crc32 = ["dep:crc32fast"]