[workspace]
resolver = "2"

members = [
    "crates/*",
    "dxe_core",
    "adv_logger",
    "sample_components",
    "uefi_test",
]

[workspace.package]
repository = "https://github.com/pop-project/uefi-dxe-core"
license = "BSD-2-Clause-Patent"
edition = "2021"
rust-version = "1.80.0"


[patch."https://github.com/pop-project/uefi-sdk"]
uefi_sdk = { path = "D:\\Repositories\\uefi-sdk\\uefi_sdk" }

[workspace.dependencies]
uefi_sdk = { git = "https://github.com/pop-project/uefi-sdk", rev = "v0.1.3" }
uefi_cpu = { git = "https://github.com/pop-project/uefi-core.git", rev = "v7.0.1" }
uefi_debugger = { git = "https://github.com/pop-project/uefi-core.git", rev = "v7.0.1" }
section_extractor = { git = "https://github.com/pop-project/uefi-core.git", rev = "v7.0.1" }
corosensei = { git = "https://github.com/pop-project/uefi-corosensei.git", rev = "d27241e17a5f3c0703fe9871e6f68cd838c05c6d", default-features = false }

uefi_test_macro = { path = "crates/uefi_test_macro", version = "5.0.0" }
uefi_test = { path = "uefi_test", version = "5.0.0" }
uefi_collections = { path = "crates/uefi_collections", version = "5.0.0", default-features = false }
uefi_depex = { path = "crates/uefi_depex", version = "5.0.0" }
uefi_device_path = { path = "crates/uefi_device_path", version = "5.0.0" }
uefi_component_interface = { path = "crates/uefi_component_interface", version = "5.0.0" }
uefi_performance = { path = "crates/uefi_performance", version = "0.1.0" }

adv_logger = { path = "adv_logger" }
sample_components = { path = "sample_components" }

ahash = { version = "^0.8", default-features = false, features = [
    "compile-time-rng",
] }
crc32fast = { version = "^1", default-features = false }
criterion = "^0.5"
goblin = { version = "^0.9", default-features = false, features = [
    "pe32",
    "pe64",
    "te",
] }
lazy_static = { version = "^1", features = ["spin_no_std"] }
linked_list_allocator = "^0.10"
log = { version = "^0.4", default-features = false }
mockall = "0.13.0"
mu_pi = { git = "https://github.com/microsoft/mu_rust_pi.git", tag = "v5.1.1" }
mu_rust_helpers = { git = "https://github.com/microsoft/mu_rust_helpers.git", tag = "v1.2.0" }
rand = "^0.8"
r-efi = { version = "^5", default-features = false }
scroll = { version = "^0.12", default-features = false, features = ["derive"] }
spin = "^0.5"
uint = "^0.10"
uuid = { version = "^1", default-features = false }

syn = "^2"
linkme = "^0.3.29"
quote = "^1"
proc-macro2 = "^1"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
