[workspace]
resolver = "2"

members = [
    "crates/*",
    "dxe_core",
    "adv_logger",
    "sample_components",
]

[workspace.package]
repository = "https://github.com/pop-project/uefi-dxe-core"
license = "BSD-2-Clause-Patent"
edition = "2021"
rust-version = "1.80.0"

[workspace.dependencies]
uefi_cpu_init = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_core = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_interrupt = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
uefi_logger = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
section_extractor = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
serial_writer = {git = "https://github.com/pop-project/uefi-core.git", rev = "6caab58b605aedb252f21ffe52c8e8524e89a58e"}
corosensei = {git = "https://github.com/pop-project/uefi-corosensei.git", rev = "d27241e17a5f3c0703fe9871e6f68cd838c05c6d", default-features = false }

uefi_collections = { path = "crates/uefi_collections", version = "0.1.9", default-features = false }
uefi_tpl_lock = { path = "crates/uefi_tpl_lock", version = "0.1.9" }
uefi_depex = { path = "crates/uefi_depex", version = "0.1.9" }
uefi_device_path = { path = "crates/uefi_device_path", version = "0.1.9" }
uefi_event = { path = "crates/uefi_event", version = "0.1.9" }
uefi_gcd = { path = "crates/uefi_gcd", version = "0.1.9" }
uefi_pecoff = { path = "crates/uefi_pecoff", version = "0.1.9" }
uefi_protocol_db = { path = "crates/uefi_protocol_db", version = "0.1.9" }
uefi_allocator = { path = "crates/uefi_allocator", version = "0.1.9" }
uefi_component_interface = { path = "crates/uefi_component_interface", version = "0.1.9" }

adv_logger = { path = "adv_logger" }
sample_components = { path = "sample_components" }

ahash = {version = "^0.8", default-features = false, features = ["compile-time-rng"]}
crc32fast = { version = "^1", default-features = false }
goblin = { version = "^0.9", default-features = false, features = ["pe32", "pe64", "te"] }
lazy_static = { version = "^1", features = ["spin_no_std"] }
linked_list_allocator = "^0.10"
log = { version = "^0.4", default-features = false, features = ["release_max_level_warn"]}
mu_pi = {git = "https://github.com/microsoft/mu_rust_pi.git", tag = "v5.0.1"}
mu_rust_helpers = { git = "https://github.com/microsoft/mu_rust_helpers.git", tag = "v1.2.0" }
r-efi = { version = "^5", default-features = false }
scroll = { version = "^0.12", default-features = false, features = ["derive"]}
spin = "^0.5"
uuid = { version = "^1", default-features = false }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
