[workspace]
resolver = "2"

members = [
    "crates/*",
    "dxe_core",
    "adv_logger",
    "sample_components",
    "uefi_test",
]

[workspace.package]
version = "7.1.2"
publish = ["UefiRust"]
repository = "https://github.com/OpenDevicePartnership/uefi-dxe-core"
license = "BSD-2-Clause-Patent"
edition = "2021"
rust-version = "1.80.0"

[workspace.dependencies]
section_extractor = { version = "9.0.2" }
uefi_sdk = { version = "1.0.1" }
uefi_cpu = { version = "9.0.2" }
uefi_debugger = { version = "9.0.2" }
uefi_corosensei = { version = "0.1", default-features = false }

adv_logger = { path = "adv_logger", version = "7" }
sample_components = { path = "sample_components", version = "7" }
uefi_collections = { path = "crates/uefi_collections", version = "7", default-features = false }
uefi_component_interface = { path = "crates/uefi_component_interface", version = "7" }
uefi_depex = { path = "crates/uefi_depex", version = "7" }
uefi_device_path = { path = "crates/uefi_device_path", version = "7" }
uefi_performance = { path = "crates/uefi_performance", version = "7" }
uefi_test = { path = "uefi_test", version = "7" }
uefi_test_macro = { path = "crates/uefi_test_macro", version = "7" }

arm-gic = { version="0.1.2" }

ahash = { version = "^0.8", default-features = false, features = [
    "compile-time-rng",
] }
crc32fast = { version = "^1", default-features = false }
criterion = "^0.5"
goblin = { version = "^0.9", default-features = false, features = [
    "pe32",
    "pe64",
    "te",
] }
lazy_static = { version = "^1", features = ["spin_no_std"] }
linked_list_allocator = "^0.10"
log = { version = "^0.4", default-features = false }
mockall = "0.13.0"
mu_pi = { version = "^5.2" }
mu_rust_helpers = { version = "2" }
paging = { version = "1.0.1" }
rand = "^0.8"
r-efi = { version = "^5.2.0", default-features = false }
scroll = { version = "^0.12", default-features = false, features = ["derive"] }
spin = "^0.9"
uint = "^0.10"
uuid = { version = "^1", default-features = false }

syn = "^2"
linkme = "^0.3.29"
quote = "^1"
proc-macro2 = "^1"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
