[package]
name = "dxe_component_interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = { workspace = true }
uefi_core = { workspace = true }