# Copyright (c) Microsoft Corporation. All rights reserved.
[package]
name = "usb_hid"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "USB HID driver that produces the HidIo protocol as a Patina component."

[lints]
workspace = true

[dependencies]
log = { workspace = true }
patina = { workspace = true }
r-efi = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
patina = { workspace = true, features = ["mockall", "test-stubs"] }
