[package]
name = "uefi_debugger"
version = "7.0.1"
license.workspace = true
repository.workspace = true

[lib]
name = "uefi_debugger"
path = "src/lib.rs"

[dependencies]
gdbstub = { version = "0.7.3", default-features = false }
uefi_sdk = { workspace = true }
uefi_cpu = { workspace = true }
log = { workspace = true }
spin = { workspace = true }
paging = { workspace = true  }

[features]
default = ["windbg_workarounds"]
windbg_workarounds = []
