[package]
name = "uefi_debugger"
version = "8.0.0"
edition = "2021"
description = "Debugger implementation for a UEFI Core."
license.workspace = true
repository.workspace = true

[lib]
name = "uefi_debugger"
path = "src/lib.rs"

[dependencies]
cfg-if = { workspace = true }
gdbstub = { version = "0.7.3", default-features = false }
uefi_sdk = { workspace = true }
uefi_cpu = { workspace = true }
log = { workspace = true }
spin = { workspace = true }
paging = { workspace = true  }

[dev-dependencies]
mockall = { workspace = true }

[features]
default = ["windbg_workarounds"]
windbg_workarounds = []
