[package]
name = "patina_boot_services"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Rust-friendly UEFI Boot Service wrappers."

[features]
default = []
global_allocator = []
mockall = ["dep:mockall"]

[dependencies]
patina_uefi_protocol = { workspace = true}
r-efi = { workspace = true }
mockall = { workspace = true, optional = true }

[dev-dependencies]
mockall = { workspace = true }
