[package]
name = "uefi_test_macro"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
readme = "README.md"
description = "Proc macros for UEFI testing."

[lib]
proc-macro = true

[features]
default = []
off = []

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
