[package]
name = "uefi_logger"
version = "0.2.0"
edition = "2021"
readme = "README.md"
description = "og implementations for the pure rust DXE core."
license.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
features = ["doc", "std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "uefi_logger"
path = "src/lib.rs"

[dependencies]
log = { workspace = true }
uefi_core = { workspace = true }

[features]
default = []
std = []
