[package]
name = "boot_services"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Rust-friendly UEFI Boot Service wrappers."

[lib]
path = "src/boot_services.rs"

[features]
default = []
global_allocator = []
mockall = ["dep:mockall"]

[dependencies]
uefi_protocol = { workspace=true }

r-efi = { workspace = true }
mockall = { version = "*", optional = true }

[dev-dependencies]
mockall = { version = "0.13.0" }
