[package]
name = "boot_services"
version = "0.1.4"
edition = "2021"

[lib]
path = "src/boot_services.rs"

[features]
default = []
global_allocator = []
mockall = ["dep:mockall"]

[dependencies]
protocol = { workspace = true }

r-efi = { workspace = true }
mockall = { version = "*", optional = true }

[dev-dependencies]
mockall = { version = "0.13.0" }
