[package]
name = "uefi_core"
version = "1.0.0"
edition = "2021"
readme = "README.md"
description = "Core definitions pure rust UEFI development."
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r-efi = { workspace = true }

[features]
default = []
