
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.EmbarkStudios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.OpenDevicePartnership]
url = "https://raw.githubusercontent.com/OpenDevicePartnership/rust-crate-audits/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aarch64-cpu]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.arm-gic]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "4.0.2"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-run"

[[exemptions.compile-time]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.gdbstub]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.171"
criteria = "safe-to-run"

[[exemptions.linked_list_allocator]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.managed]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.mockall]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.mockall_derive]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.mu_rust_helpers]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_decompress]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_guid]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_perf_timer]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.1"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.raw-cpuid]]
version = "10.7.0"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spinning_top]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.tock-registers]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.uart_16550]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.volatile]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.x86]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.x86_64]]
version = "0.14.12"
criteria = "safe-to-deploy"
