
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.EmbarkStudios]
url = "https://raw.githubusercontent.com/EmbarkStudios/rust-ecosystem/main/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aarch64-cpu]]
version = "10.0.0"
criteria = "safe-to-deploy"

[[exemptions.alloc-no-stdlib]]
version = "2.0.4"
criteria = "safe-to-run"

[[exemptions.anes]]
version = "0.1.6"
criteria = "safe-to-run"

[[exemptions.arm-gic]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.bitfield-struct]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.bitvec]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.boot_services]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.boot_services]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.brotli-decompressor]]
version = "4.0.2"
criteria = "safe-to-run"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-run"

[[exemptions.compile-time]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.crossbeam-epoch]]
version = "0.9.18"
criteria = "safe-to-run"

[[exemptions.crossbeam-utils]]
version = "0.8.21"
criteria = "safe-to-run"

[[exemptions.deranged]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.driver_binding]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.driver_binding]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.fallible-streaming-iterator]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.fixedbitset]]
version = "0.5.7"
criteria = "safe-to-deploy"

[[exemptions.funty]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.gdbstub]]
version = "0.7.5"
criteria = "safe-to-deploy"

[[exemptions.goblin]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.hermit-abi]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.indoc]]
version = "2.0.6"
criteria = "safe-to-deploy"

[[exemptions.is-terminal]]
version = "0.4.16"
criteria = "safe-to-run"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.171"
criteria = "safe-to-run"

[[exemptions.linked_list_allocator]]
version = "0.10.5"
criteria = "safe-to-deploy"

[[exemptions.linkme]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.linkme-impl]]
version = "0.3.32"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.managed]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-run"

[[exemptions.mockall]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.mockall_derive]]
version = "0.13.1"
criteria = "safe-to-run"

[[exemptions.mtrr]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.mu_pi]]
version = "5.2.1"
criteria = "safe-to-deploy"

[[exemptions.mu_rust_helpers]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_boot_services]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_decompress]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_guid]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_perf_timer]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_runtime_services]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.mu_uefi_tpl_mutex]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.1"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.paging]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.paste]]
version = "1.0.15"
criteria = "safe-to-deploy"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.predicates]]
version = "3.1.3"
criteria = "safe-to-run"

[[exemptions.predicates-core]]
version = "1.0.9"
criteria = "safe-to-run"

[[exemptions.predicates-tree]]
version = "1.0.12"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-deploy"

[[exemptions.radium]]
version = "0.7.0"
criteria = "safe-to-deploy"

[[exemptions.raw-cpuid]]
version = "10.7.0"
criteria = "safe-to-deploy"

[[exemptions.rayon]]
version = "1.10.0"
criteria = "safe-to-run"

[[exemptions.rayon-core]]
version = "1.12.1"
criteria = "safe-to-run"

[[exemptions.runtime_services]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.runtime_services]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.rustc_version]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.ryu]]
version = "1.0.20"
criteria = "safe-to-run"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.scroll]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.scroll_derive]]
version = "0.12.0"
criteria = "safe-to-deploy"

[[exemptions.section_extractor]]
version = "10.0.1"
criteria = "safe-to-run"

[[exemptions.semver]]
version = "1.0.26"
criteria = "safe-to-deploy"

[[exemptions.spin]]
version = "0.9.8"
criteria = "safe-to-deploy"

[[exemptions.spinning_top]]
version = "0.2.5"
criteria = "safe-to-deploy"

[[exemptions.stacktrace]]
version = "10.0.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.100"
criteria = "safe-to-deploy"

[[exemptions.termtree]]
version = "0.5.1"
criteria = "safe-to-run"

[[exemptions.time]]
version = "0.3.41"
criteria = "safe-to-deploy"

[[exemptions.time-core]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.time-macros]]
version = "0.2.22"
criteria = "safe-to-deploy"

[[exemptions.tock-registers]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.tpl_mutex]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.tpl_mutex]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.uart_16550]]
version = "0.3.2"
criteria = "safe-to-deploy"

[[exemptions.uefi_corosensei]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.uefi_cpu]]
version = "10.0.1"
criteria = "safe-to-deploy"

[[exemptions.uefi_debugger]]
version = "10.0.1"
criteria = "safe-to-deploy"

[[exemptions.uefi_protocol]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.uefi_protocol]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.uefi_sdk]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.uefi_sdk]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.uefi_sdk_macro]]
version = "2.2.1"
criteria = "safe-to-deploy"

[[exemptions.uefi_sdk_macro]]
version = "3.0.0"
criteria = "safe-to-deploy"

[[exemptions.uint]]
version = "0.10.0"
criteria = "safe-to-run"

[[exemptions.uuid]]
version = "1.16.0"
criteria = "safe-to-deploy"

[[exemptions.volatile]]
version = "0.4.6"
criteria = "safe-to-deploy"

[[exemptions.walkdir]]
version = "2.5.0"
criteria = "safe-to-run"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-run"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-run"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-run"

[[exemptions.wyz]]
version = "0.5.1"
criteria = "safe-to-deploy"

[[exemptions.x86]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.x86_64]]
version = "0.14.12"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.24"
criteria = "safe-to-run"

[[exemptions.zerocopy-derive]]
version = "0.8.24"
criteria = "safe-to-run"
