[workspace]
resolver = "2"

members = [
  "uefi_sdk",
  "runtime_services",
]

[workspace.package]
repository = "https://github.com/pop-project/uefi-sdk"
license = "BSD-2-Clause-Patent"
edition = "2021"
include = [
  "Cargo.toml",
  "LICENSE*",
  "README.md"
]

[workspace.dependencies]
log = { version = "^0.4", default-features = false }
r-efi = { version = "^5", default-features = false }
uart_16550 = "^0.3.2"
x86_64 = "^0.14"

runtime_services = { path="./runtime_services" }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
