[workspace]
resolver = "2"

members = ["uefi_sdk"]

[workspace.package]
repository = "https://github.com/pop-project/uefi-sdk"
license = "BSD-2-Clause-Patent"
edition = "2021"
include = [
  "Cargo.toml",
  "LICENSE*",
  "README.md"
]

[workspace.dependencies]

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
