[workspace]
resolver = "2"

members = [
  "uefi_sdk",
  "boot_services",
  "uefi_protocol",
  "runtime_services",
  "tpl_mutex"
]

[workspace.package]
repository = "https://github.com/pop-project/uefi-sdk"
license = "BSD-2-Clause-Patent"
edition = "2021"
include = [
  "Cargo.toml",
  "LICENSE*",
  "README.md"
]

[workspace.dependencies]
boot_services = { path = "./boot_services" }
uefi_protocol = { path = "./uefi_protocol"}
runtime_services = { path = "./runtime_services" }
tpl_mutex = { path = "./tpl_mutex" }

log = { version = "^0.4", default-features = false }
r-efi = { version = "^5", default-features = false }
uart_16550 = "^0.3.2"
x86_64 = { version= "=0.14.12", default-features = false, features = ["instructions"] }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
