[package]
name = "patina_uefi_protocol"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Protocol trait implementations."

[dependencies]
mu_pi = { workspace = true }
r-efi = { workspace = true }
