[package]
name = "patina_test"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
readme = "README.md"
description = "An on-platform test harness for UEFI firmware."

[features]
default = []
off = ["patina_test_macro/off"]

[dependencies]
log = { workspace = true }
patina_sdk = { workspace = true, features = ["core"] }
patina_test_macro = { workspace = true }
linkme = { workspace = true}

[dev-dependencies]
r-efi = { workspace = true }
mockall = { workspace = true }
