[package]
name = "uefi_test_macro"
version = "0.1.9"
edition = "2021"
readme = "README.md"
description = "Proc macros for the uefi_test crate."
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[features]
default = []
off = []

[dependencies]
syn = { workspace = true, features = ["full"] }
quote = { workspace = true }
proc-macro2 = { workspace = true }
