[package]
name = "uefi_pecoff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "uefi_pecoff"
path = "src/lib.rs"

[dependencies]
goblin = {workspace = true}
scroll = {workspace = true}