[package]
name = "uefi_protocol_db"
version = "2.0.0"
edition = "2021"
readme = "README.md"
description = "A Protocol Database implementation for the dxe_core."
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "uefi_protocol_db"
path = "src/lib.rs"

[dependencies]
ahash = {workspace=true}
r-efi = {workspace=true}
spin = {workspace=true}
uefi_tpl_lock = {workspace=true}


[dependencies.uuid]
default-features = false
version = "1"