[package]
name = "tpl_mutex"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Support for mutual exclusion across Task Priority Levels (TPLs)."

[lib]
path = "src/tpl_mutex.rs"

[dependencies]
r-efi = { workspace=true }
boot_services = { workspace=true }

[dev-dependencies]
mockall = { version = "0.13.0" }
boot_services = { workspace=true, features = ["mockall"]}
