[package]
name = "patina_runtime_services"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Rust-friendly UEFI Runtime Service wrappers."

[features]
default = []
global_allocator = []
mockall = ["dep:mockall"]

[dependencies]
r-efi = { workspace = true }
mockall = { workspace = true, optional = true }
fallible-streaming-iterator = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
