[package]
name = "protocol"
version = "0.1.4"
repository.workspace = true
license.workspace = true
edition.workspace = true
include.workspace = true

[lib]
path = "src/protocol.rs"

[dependencies]
r-efi = { workspace = true }