[package]
name = "patina_smbios"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
log = {workspace = true}
patina_sdk = {workspace = true}

[features]
std = []
