[package]
name = "patina_smbios"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
log = {workspace = true}
patina_sdk = {workspace = true}
bitfield = "0.19.2"
r-efi = "5.3.0"
mu_pi = {git = "https://github.com/microsoft/mu_rust_pi"}

[features]
std = []
