[book]
authors = ["Uefi Rust Team"]
language = "en"
multilingual = false
src = "src"
title = "Developing UEFI with Rust"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.playpen]
editable = true
editor = "ace"
line-numbers = true

[output.html.fold]
enable = true

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
