[package]
name = "driver_binding"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "Provides UEFI driver binding for providing protocols"

[lib]
path = "src/driver_binding.rs"

[features]
mockall = ["dep:mockall"]

[dependencies]
boot_services = { workspace = true }
uefi_protocol = { workspace = true }
r-efi = { workspace = true }
log = { workspace = true }
mockall = { workspace = true, optional = true }

[dev-dependencies]
mockall = { workspace = true }

boot_services = { workspace = true, features = ["mockall"] }
