[workspace]
resolver = "2"

members = [
  "uefi_core",
  "uefi_cpu_init",
  "uefi_logger",
  "section_extractor",
  "serial_writer", "uefi_interrupt",
]

[workspace.package]
repository = "https://github.com/pop-project/uefi-core"
license = "BSD-2-Clause-Patent"
edition = "2021"
include = [
  "Cargo.toml",
  "LICENSE*",
  "README.md"
]

[workspace.dependencies]
uefi_core = { path = "uefi_core", version = "1.0.0" }

# External Libraries
lazy_static = { version = "^1", features = ["spin_no_std"] }
log = { version = "^0.4", default-features = false }
r-efi = { version = "^5", default-features = false }
spin = "^0.9"
uart_16550 = "^0.3.2"
x86_64 = "^0.14"
mu_pi = {git = "https://github.com/microsoft/mu_rust_pi.git", tag = "v5.1.0"}
mu_rust_helpers = { git = "https://github.com/microsoft/mu_rust_helpers", tag = "v1.2.1", default-features = false}

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
