[toolchain]
channel = "1.80.0"
targets = ["x86_64-unknown-uefi", "aarch64-unknown-uefi"]
components = ["rust-src"]

[tools]
cargo-make = "0.37.21"
cargo-release = "0.25.12"
cargo-tarpaulin = "0.31.2"
