[package]
name = "uefi_sdk"
version = "0.1.3"
repository.workspace = true
license.workspace = true
edition.workspace = true
include.workspace = true

[dependencies]
log = { workspace = true }
r-efi = { workspace = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
x86_64 = { workspace = true }
uart_16550 = { workspace = true }

[features]
std = []
doc = []
