[package]
name = "uefi_sdk"
version = "0.1.4"
repository.workspace = true
license.workspace = true
edition.workspace = true
include.workspace = true

[dependencies]
boot_services = { workspace = true }
uefi_protocol = { workspace = true }
runtime_services = { workspace = true }
tpl_mutex = { workspace = true }

log = { workspace = true }
r-efi = { workspace = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
x86_64 = { workspace = true }
uart_16550 = { workspace = true }

[features]
std = []
doc = []
