[package]
name = "uefi_sdk"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
publish.workspace = true
description = "UEFI Software Development Kit (SDK) that provides common types and functionality used in UEFI development."

[dependencies]
boot_services = { workspace = true }
uefi_protocol = { workspace = true }
runtime_services = { workspace = true }
tpl_mutex = { workspace = true }

log = { workspace = true }
r-efi = { workspace = true }

[target.'cfg(target_arch="x86_64")'.dependencies]
x86_64 = { workspace = true }
uart_16550 = { workspace = true }

[features]
std = []
doc = []
