[package]
name = "uefi_tpl_lock"
version = "2.0.2"
edition = "2021"
readme = "README.md"
description = "A Mutex implementation that has context of the current Task Priority Level to prevent deadlocking."
license.workspace = true
repository.workspace = true

[lib]
name = "tpl_lock"
path = "src/lib.rs"

[dependencies]
r-efi = { workspace = true }
log = { workspace = true }