[package]
name = "uefi_sdk_macro"
version.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "Proc-macro crate for the UEFI Software Development Kit (SDK)."

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }
